### ISSUE TITLE
Cannot start Jupyter on Mac

### ISSUE THREAD

**Issue by philohistoria** [jat255/JupyterHere#3]
I think your plugin is a great idea but I cannot make it work on Mac. Here is the error message:
```
Command 'JupyterHere' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 128, in _execute_command
  File "/Users/han/Library/Application Support/fman/Plugins/Third-party/JupyterHere/jupyterhere/__init__.py", line 15, in __call__
    r'--notebook-dir="{}"'.format(cd))
  File "subprocess.py", line 247, in call
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter-notebook --notebook-dir="file:///Users/han/Codes/fastText/result"'
```

And I am sure that the `jupyter-notebook` is on my `PATH`. Tested it within my terminal.

**Comment by philohistoria** [comment]
I figure outed the solution. On mac; 

The file path should not start with `"file://" ` . 

Also I use pyenv so this line might help to explicitly add `jupyter-notebook' path to `PATH`

```
os.environ["PATH"] += os.pathsep + "/Users/han/.pyenv/shims/"
```
